
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class Doc_login extends javax.swing.JFrame {

    /**
     * Creates new form Doc_login
     */
    public Doc_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_text = new javax.swing.JLabel();
        pass_text = new javax.swing.JLabel();
        user_d = new javax.swing.JTextField();
        pass_d = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        login_d = new javax.swing.JButton();
        back_d = new javax.swing.JButton();
        showpass_d = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1032, 595));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user_text.setText("USERNAME");
        getContentPane().add(user_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 234, -1, 38));

        pass_text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pass_text.setText("PASSWORD");
        getContentPane().add(pass_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 304, -1, 38));

        user_d.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(user_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 234, 173, -1));

        pass_d.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(pass_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 304, 173, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("WELCOME !!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 134, -1, -1));

        login_d.setBackground(new java.awt.Color(102, 204, 0));
        login_d.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        login_d.setText("LOGIN");
        login_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_dActionPerformed(evt);
            }
        });
        getContentPane().add(login_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 397, -1, -1));

        back_d.setBackground(new java.awt.Color(255, 102, 102));
        back_d.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        back_d.setText("Back");
        back_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_dActionPerformed(evt);
            }
        });
        getContentPane().add(back_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 397, 84, -1));

        showpass_d.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showpass_d.setText("ShowPass");
        showpass_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass_dActionPerformed(evt);
            }
        });
        getContentPane().add(showpass_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 315, 85, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel1.setText("PAT BUDDY");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIP (1).jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 666, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        jPanel2.setBackground(new java.awt.Color(237, 231, 235));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1040, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_dActionPerformed
        if(String.valueOf(pass_d.getPassword()).equals("admin") && user_d.getText().equals("admin")){
            Dochome home = new Dochome();
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Username or Password is wrong");
        }
    }//GEN-LAST:event_login_dActionPerformed

    private void back_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_dActionPerformed
        Home_Page page = new Home_Page();

        page.setVisible(true);
        page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_back_dActionPerformed

    private void showpass_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass_dActionPerformed
        if (showpass_d.isSelected()){
            pass_d.setEchoChar((char)0);
        }
        else{
            pass_d.setEchoChar('*');
        }
    }//GEN-LAST:event_showpass_dActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doc_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doc_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doc_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doc_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doc_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_d;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_d;
    private javax.swing.JPasswordField pass_d;
    private javax.swing.JLabel pass_text;
    private javax.swing.JCheckBox showpass_d;
    private javax.swing.JTextField user_d;
    private javax.swing.JLabel user_text;
    // End of variables declaration//GEN-END:variables
}
