
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class PatLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form PatLogin
     */
    public PatLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_p = new javax.swing.JTextField();
        pass_p = new javax.swing.JPasswordField();
        showpass_d = new javax.swing.JCheckBox();
        login_d = new javax.swing.JButton();
        back_d = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 900, 511));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel1.setText("PAT BUDDY");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("USERNAME ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 204, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 288, -1, -1));

        user_p.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        getContentPane().add(user_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 204, 164, 43));

        pass_p.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        getContentPane().add(pass_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 288, 164, 43));

        showpass_d.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showpass_d.setText("ShowPass");
        showpass_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass_dActionPerformed(evt);
            }
        });
        getContentPane().add(showpass_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 296, 85, -1));

        login_d.setBackground(new java.awt.Color(102, 204, 0));
        login_d.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        login_d.setText("LOGIN");
        login_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_dActionPerformed(evt);
            }
        });
        getContentPane().add(login_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 396, -1, -1));

        back_d.setBackground(new java.awt.Color(255, 102, 102));
        back_d.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        back_d.setText("Back");
        back_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_dActionPerformed(evt);
            }
        });
        getContentPane().add(back_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 396, 84, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel5.setText("Your Username and Password is your Phone Number !!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 124, -1, -1));

        jPanel2.setBackground(new java.awt.Color(237, 231, 235));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 910, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpass_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass_dActionPerformed
        if (showpass_d.isSelected()){
            pass_p.setEchoChar((char)0);
        }
        else{
            pass_p.setEchoChar('*');
        }
    }//GEN-LAST:event_showpass_dActionPerformed
    public boolean valid(){
        
        if(user_p.getText().equals("")|| String.valueOf(pass_p.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null,"One or More Field Are Empty");
            return false;
        }      
        return true;
    }
    
    private void login_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_dActionPerformed
        
        if(valid()){
               
            Connection con = myConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;

            try {
                ps = con.prepareStatement("SELECT * FROM `patientdetails` WHERE `phone no.`= ?");
                ps.setString(1,user_p.getText());
                ps.setString(1,String.valueOf(pass_p.getPassword()));
                rs = ps.executeQuery();
                if(rs.next()){
                    Connection add = myConnection.getConnection();
                    PreparedStatement addps;
                    try {
                        addps = add.prepareStatement("INSERT INTO `signup`( `UserName`) VALUES (?)");
                        addps.setString(1,user_p.getText());
                        addps.executeUpdate();
                    }catch (SQLException ex){
                        System.out.println(ex.getMessage());
                    }
                    PatHome patt = new PatHome();
                    patt.setVisible(true);
                    patt.setLocationRelativeTo(null);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"               Login Error !!\nThe Username or Pass word is wrong \nor You are not registered at our clinic");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Pat_login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_login_dActionPerformed

    private void back_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_dActionPerformed
        Home_Page page = new Home_Page();

        page.setVisible(true);
        page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_back_dActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_d;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_d;
    private javax.swing.JPasswordField pass_p;
    private javax.swing.JCheckBox showpass_d;
    private javax.swing.JTextField user_p;
    // End of variables declaration//GEN-END:variables
}
